- type: job
  id: BoSWestScribe
  setPreference: true
  name: job-name-bos-west-scribe
  description: job-description-bos-west-scribe
  playTimeTracker: BoSWestScribe
  requirements:
    - !type:CharacterSpeciesRequirement
      species:
      - Human
    - !type:CharacterDepartmentTimeRequirement
      department: BrotherhoodMidwest
      min: 54000 # 15 hours
    - !type:CharacterLogicOrRequirement
      requirements:
        - !type:CharacterSpeciesRequirement
          species:
            - Human
  startingGear: BoSWestScribeGear
  alwaysUseSpawner: true
  icon: "JobIconBosMScriptor" # Corvax-Change
  supervisors: job-supervisors-bos-mid
  access:
  - BoSWest
  special:
  - !type:AddComponentSpecial
    components:
      - type: NpcFactionMember
        factions:
          - BrotherhoodWest
      - type: CPRTraining

- type: startingGear
  id: BoSWestScribeGear
  equipment:
    jumpsuit: N14ClothingUniformJumpsuitBOSScribe
    back: N14ClothingBackpackSatchelMilitary # Corvax-Change
    shoes: N14ClothingBootsLeather
    pocket1: NCRBoSMidwestScribekits
    id: N14IDBrotherhoodHolotag
    ears: N14ClothingHeadsetBOSMidwest
  storage: # Corvax-Change
    back:
    - N14BoxPlasticFilledMilitary

- type: playTimeTracker
  id: BoSWestScribe
